name: Cypress functional tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 19 * * 1-5'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          spec: |
            cypress/integration/functional_testing/*.spec.js
